modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="lolocraftv"
version="5.0.0"
displayName="LoloCraftV"
credits="Copyright Fox Inc. 2022"
displayURL="http://lolocraft.derlolo.de/lolocraft/lolocraft-v/"
logoFile="logo.png"
authors="DerLoloHD"
description='''
The new Galaxy is here!
'''

[[dependencies.lolocraftv]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




