modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="lolocraftv"
version="5.0.1"
displayName="LoloCraftV"
credits="Fuchsiii´s 2022"
displayURL="http://fuchsiii.de/LoloCraft-Mod/LoloCraft.html"
updateJSONURL="https://raw.githubusercontent.com/Fuchsi51/LoloCraft/main/Update.json"
logoFile="logo.png"
authors="Fuchsiii51"
description='''
The new Galaxy is here!
'''

[[dependencies.lolocraftv]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5]"
    ordering="NONE"
    side="BOTH"




